LogBook/Models/ErrorViewModel.cs
using System;

namespace LogBook.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LogBook/Models/LogPost.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LogBook.Models
{
    public class LogPost
    {
        public Guid Id { get; set; }
        public DateTimeOffset CreateTime { get; set; }
        public List<LogPostQuestion> Questions { get; set; }
        public Dictionary<LogPostQuestion, LogPostAnswer> QAList { get; set; }
        public string Note { get; set; }
        public LogPost(LogPostTemplate template)
        {
            CreateTime = DateTimeOffset.Now;
            Id = Guid.NewGuid();
            QAList = new Dictionary<LogPostQuestion, LogPostAnswer>();
            Questions = template.QuestionList;
        }
        public void AnswerQuestion(LogPostQuestion q, int? score=null, string text=null)
        {
            LogPostAnswer a = new LogPostAnswer(q.Id, score, text);

            if (QAList.ContainsKey(q))
                QAList.Remove(q);
            QAList.Add(q, a);
        }
        public List<Tag> GetTags()
        {
            return Questions.SelectMany(x => x.Tags).Distinct().ToList();
        }
    }


}

LogBook/Models/LogPostAnswer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LogBook.Models
{
    public class LogPostAnswer
    {
        public Guid Id { get; set; }
        public Guid Question { get; set; }
        public int? Score { get; set; }
        public string Text { get; set; }
        public LogPostAnswer(Guid question, int? score=null, string text=null)
        {
            Id = Guid.NewGuid();
            Question = question;
            Score = score;
            Text = text;
        }
        public override string ToString()
        {
            if (Text == null)
                Text = "";
            if (Score == null)
                return Text;
            return Score.ToString();
        }
    }
}

LogBook/Models/LogPostQuestion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LogBook.Models
{
    public class LogPostQuestion
    {
        public string Question { get; set; }
        public Guid Id { get; set; }
        public List<Tag> Tags { get; set; }
        public bool Scorable { get; set; }
        public int? MinScore { get; set; }
        public int? MaxScore { get; set; }


        public LogPostQuestion(string question, List<Tag> tags) : this(question, tags, null, null )
        { }
        public LogPostQuestion(string question, List<Tag> tags, int? minScore, int? maxScore)
        {
            Question = question;
            Tags = tags;
            bool scoreable = false;
            if (minScore != null && maxScore != null) scoreable = true;
            if (scoreable)
            {
                MinScore = minScore;
                MaxScore = maxScore;
            }
        }
    }
}

LogBook/Models/LogPostTemplate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LogBook.Models
{
    public class LogPostTemplate
    {
        public Guid Id { get; set; }
        public DateTimeOffset CreateTime { get; set; }
        public List<LogPostQuestion> QuestionList { get; set; }
        public LogPostTemplate()
        {
            CreateTime = DateTimeOffset.Now;
            Id = Guid.NewGuid();
            QuestionList = new List<LogPostQuestion>();
        }

        public void AddQuestion(LogPostQuestion q)
        {
            QuestionList.Add(q);
        }
        public List<Tag> GetTags()
        {
            return QuestionList.SelectMany(x => x.Tags).Distinct().ToList();
        }
    }
}

LogBook/Models/LogPostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LogBook.Models
{
    public class LogPostViewModel
    {
        public List<LogPost> Posts { get; set; }
    }
}

LogBook/Models/Tag.cs
using System;

namespace LogBook.Models
{
    public class Tag
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Tag(string name)
        {
            Name = name;
            Id = Guid.NewGuid();
        }
    }
}

LogBook/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LogBook.Models;

namespace LogBook.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LogBook/Controllers/LogBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LogBook.Models;
using LogBook.Services;
using Microsoft.AspNetCore.Mvc;

namespace LogBook.Controllers
{
    public class LogBookController : Controller
    {
        private readonly ILogBookService _logBookService;
        public LogBookController(ILogBookService logBookService)
        {
            _logBookService = logBookService;
        }
        public async Task<IActionResult> Index()
        {
            var posts = await _logBookService.GetPostsAsync();
            var model = new LogPostViewModel
            {
                Posts = posts
            
            };
            return View(model);
        }
    }
}

LogBook/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LogBook/Views/LogBook/Index.cshtml
@model LogBook.Models.LogPostViewModel
@using  Humanizer

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>CreateTime</th>
            <th>Note</th>
            <th>Questions</th>

            <th>Tags</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Posts)
        {
            <tr>
                <td>@item.CreateTime.Humanize()</td>
                <td>@item.Note</td>
                <td>
                    <table>
                        <thead>
                            <tr>
                            </tr>
                        </thead>
                        @foreach (var qa in item.QAList)
                        {
                            <tr>
                                <td><h5>@qa.Key.Question</h5></td>
                                <!--td>@qa.Value.ToString()</td-->
                            <td>
                                @if (qa.Value.Score != null)
                                {
                                   @qa.Key.MinScore <input type="range" min=@qa.Key.MinScore max=@qa.Key.MaxScore value=@qa.Value.Score disabled="disabled" /> @qa.Key.MaxScore
                                }
                                else
                                {
                                    @qa.Value.ToString()
                                }
                            </td>
                            </tr>
                        }
                    </table>
                </td>

                <td>
                    @foreach (var tag in item.GetTags())
                    {
                        <span> @tag.Name</span>
                    }
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

LogBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LogBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LogBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogBook" asp-action="Index">LogBook</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - LogBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>